config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  
  get 'about' => 'pages#about'
  
  resources :articles#this line gives the option to Create, Read, Update , Delete articles
  get 'signup' => 'users#new'
  
  resources :users, except: [:new]

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/car.rb
class Car < ActiveRecord::Base
  validates :title, presence: true, length: { minimum:3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 200 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  before_save { self.email = email.downcase }
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 5, maximum: 25 }
  VALID_EMAIL_REGEX=/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index
    #NOTE : ---Using a plural instance variable is articles--
    @articles = Article.paginate(page: params[:page], per_page: 5)
    
  end
  
  def new
    @article = Article.new
  end
  
  def create
    debugger
    #render plain: params[:article].inspect=============rendering of the data entered in Title and description------
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      #something
      flash[:success] = "Article was successfully Created!"
      redirect_to article_path(@article)
    else
      render :new
    end
    # @article.save
    # redirect_to article_path(@article)
  end
  
  def show
    @article = Article.find(params[:id])
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:danger] = "The article was succesfully deleted!"
    redirect_to articles_path
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:success] = "Article updated Successfully"
      redirect_to article_path(@article)
    else
      render :edit
    end
      
  end
  
  private
  
  def set_article
    @article = Article.find(params[:id])  
  end
  
  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    
  end
  
  def about
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.paginate(page: params[:page], per_page: 1)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to Alpha Blog #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Account details updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end
  
  def show
    @user = User.find(params[:id])
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 1)
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, class: "img-circle", alt: user.username)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
    <div class="row">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
            <small>Created By : <%= article.user.username if article.user %>,
                  <%= time_ago_in_words(article.created_at) %> ago,
                  Last Updated : <%= time_ago_in_words(article.updated_at) %></small>  
          </div>
        </div>
        <div class="article-actions">
          <%= link_to "Edit this Article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete this Article", article_path(article), 
                                          method: :delete, 
                                          data: { confirm: "Are you sure you want to delet this article ?" }, 
                                          class: "btn btn-xs btn-danger" %>
        </div>
      </div>
    </div>
    
  <% end %>

app/views/articles/_form.html.erb
<!-------------------below is the error handling / show section ------------------>

<%= render 'shared/errors', obj: @article%> <!--render the _errors.html.erb file under the views/shared section------->

<!-------------------above are the errors------------------>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :title %>
      </div>
      <div class="col-md-8">
        <%= f.text_field :title, class: "form-control", placeholder: "Title for the Article", autofocus: true %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :description %>
      </div>
      <div class="col-md-8">
        <%= f.text_area :description, rows: 20, class: "form-control one_text_area", placeholder: "Description for the Article" %>
      </div>
      
    </div>
    
    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
       <%= f.submit class: "btn btn-primary" %> 
      </div>
    </div>
    
    <% end %>
    <div class="col-md-offset-2">
      [ <%= link_to "Cancel and Return to Articles List", articles_path %> ]
    </div>
    
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="center">Edit your article here</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Articles List</h1>
<!--<p><%= link_to "Create New Article" ,new_article_path %></p>-->

  <!--<tr>
    <th>Title</th>
    <th>Description</th>
  </tr>-->
  
<div align="center">
  <%= will_paginate %>
</div>
  
<%= render 'article' , obj: @articles %>

<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">A new article entry page</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title : <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
 <% if @article.user %>
  <ul class="listing">
    <div class="row center">
      <div class="col-md-4 col-md-offset-4">
        <li>Created By : </li>
        <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
        <li class="article-title">
          <%= link_to @article.user.username, user_path(@article.user) %>
        </li>
        <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
      </div>
    </div>
   </ul>
  <% end %>
  <h4 class="center"><strong>Description : </strong></h4>
  <hr>
   <%= simple_format(@article.description) %>
   <div class="article-actions">
    <%= link_to "Edit this Article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to "Back to Articles List", articles_path , class: "btn btn-xs btn-success" %>
    <%= link_to "Delete this Article", article_path(@article), 
                                          method: :delete, 
                                          data: { confirm: "Are you sure you want to delet this article ?" }, 
                                          class: "btn btn-xs btn-danger" %>
   </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>Copyright &copy<a href="https://www.udemy.com">Complete Ruby on Rails Developer Course</a></small>
    <nav>
      <ul>
        <li>
          <%= link_to 'About', about_path %>
        </li>
      </ul>
    </nav>
  </footer>
  
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <% flash.each do |name, message| %>
    <div class='alert alert-<%= "#{name}" %>'>
      <a href='#' class='close' data-dismiss='alert'>&#215;</a>
      <%= content_tag :div, message, :id => "flash_#{name}" if message.is_a?(String) %>
    </div>
    <% end %>
  </div>
</div>



 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" id="logo" href="#">Alpha-Blog</a>-->
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li><a href="#">Link <span class="sr-only">(current)</span></a></li>-->
        <li><%= link_to "Articles", articles_path %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <!--<li><a href="#">Action</a></li>-->
            <li><%= link_to "New Article", new_article_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>  
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  

</body>
</html>

app/views/pages/about.html.erb
<h1>This is my About page</h1>

<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<!--<h1>This is my Home page</h1>-->


<div class="center jumbotron">
  <h1 id='clr'>Alpha Blog</h1>
  <!--<p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>-->
  <%= link_to "Sign Up Now", "#", class: "btn btn-primary btn-lg" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= pluralize(obj.errors.count, "error") %>
          prohibited this article from being saved :
        </h2>
        <div class="panel-body">
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

  
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %> <!--render the _errors.html.erb file under the views/shared section------->

<!-------------------above are the errors------------------>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :username %>
      </div>
      <div class="col-md-8">
        <%= f.text_field :username, class: "form-control", placeholder: "Enter a Username", autofocus: true %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :email %>
      </div>
      <div class="col-md-8">
        <%= f.email_field :email, class: "form-control one_text_area", placeholder: "Enter E-mail ID" %>
      </div>
      
    </div>
    
    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :password %>
      </div>
      <div class="col-md-8">
        <%= f.password_field :password, class: "form-control one_text_area", placeholder: "Enter password" %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
       <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "btn btn-primary") %> 
      </div>
    </div>
    
    <% end %>
    <div class="col-md-offset-2">
      [ <%= link_to "Cancel and Return to Articles List", articles_path %> ]
    </div>
    
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your User details</h1>

<!-------------------below is the error handling / show section ------------------>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center"> All Bloggers</h1>
<div align="center">
  <%= will_paginate %>
</div>
<div class="center">
  <% @users.each do |user| %>
  <ul class="listing">
    <div class="row">
      <div class="well col-md-4 col-md-offset-4">
        <li><%= link_to gravatar_for(user), user_path(user) %></li>
        <li class="article-title">
          <%= link_to user.username, user_path(user) %>
        </li>
        <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
      </div>
    </div>
  </ul>
  <% end %>
</div>
<div align="center">
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign Up</h1>

<!-------------------below is the error handling / show section ------------------>

<%= render 'shared/errors', obj: @user %> <!--render the _errors.html.erb file under the views/shared section------->

<!-------------------above are the errors------------------>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :username %>
      </div>
      <div class="col-md-8">
        <%= f.text_field :username, class: "form-control", placeholder: "Enter a Username", autofocus: true %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :email %>
      </div>
      <div class="col-md-8">
        <%= f.email_field :email, class: "form-control one_text_area", placeholder: "Enter E-mail ID" %>
      </div>
      
    </div>
    
    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :password %>
      </div>
      <div class="col-md-8">
        <%= f.password_field :password, class: "form-control one_text_area", placeholder: "Enter password" %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
       <%= f.submit "Sign Up", class: "btn btn-primary" %> 
      </div>
    </div>
    
    <% end %>
    <div class="col-md-offset-2">
      [ <%= link_to "Cancel and Return to Articles List", articles_path %> ]
    </div>
    
  </div>
</div>

app/views/users/show.html.erb
<h1 align="center"> Welcome to <%= @user.username %>'s page</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user %>
  </div>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4>
<div class="center">
  <%= will_paginate @user_articles %>
</div>

<%= render 'articles/article', obj:@user_articles %> 

<div class="center">
  <%= will_paginate @user_articles %>
</div>